/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AlumnoData;
import Modelo.Alumno;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia
 */
public class FormularioAlumno extends javax.swing.JInternalFrame {

    private AlumnoData ad;

    public FormularioAlumno() {
        initComponents();
        ad = new AlumnoData();
    }

    public void activarCampos() {
        jtfLegajo.setEnabled(true);
        jtfDni.setEnabled(true);
        jtfNombre.setEnabled(true);
        jtfApellido.setEnabled(true);
        jdcFecha.setEnabled(true);
        jcbEstado.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbGuardar.setEnabled(true);
    }

    public void desactivarCampos() {
        jtfLegajo.setEnabled(false);
        jtfDni.setEnabled(false);
        jtfNombre.setEnabled(false);
        jtfApellido.setEnabled(false);
        jdcFecha.setEnabled(false);
        jcbEstado.setEnabled(false);
        jbBuscar.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbActualizar.setEnabled(false);

    }

    public void limpiarCampos() {
        jtfLegajo.setText("");
        jtfDni.setText("");
        jtfNombre.setText("");
        jtfApellido.setText("");
        jdcFecha.setDate(null);
        jcbEstado.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JCheckBox();
        jtfLegajo = new javax.swing.JTextField();
        jtfDni = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jdcFecha = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Formulario Alumnos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 45));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Legajo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("DNI:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha de nac.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jcbEstado.setEnabled(false);
        jPanel1.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 26, 34));

        jtfLegajo.setBackground(new java.awt.Color(102, 102, 255));
        jtfLegajo.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jtfLegajo.setForeground(new java.awt.Color(255, 255, 255));
        jtfLegajo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfLegajo.setEnabled(false);
        jtfLegajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfLegajoFocusLost(evt);
            }
        });
        jPanel1.add(jtfLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 195, -1));

        jtfDni.setBackground(new java.awt.Color(102, 102, 255));
        jtfDni.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jtfDni.setForeground(new java.awt.Color(255, 255, 255));
        jtfDni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfDni.setEnabled(false);
        jtfDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDniFocusLost(evt);
            }
        });
        jPanel1.add(jtfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 195, -1));

        jtfNombre.setBackground(new java.awt.Color(102, 102, 255));
        jtfNombre.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jtfNombre.setForeground(new java.awt.Color(255, 255, 255));
        jtfNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNombre.setEnabled(false);
        jPanel1.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 195, -1));

        jtfApellido.setBackground(new java.awt.Color(102, 102, 255));
        jtfApellido.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jtfApellido.setForeground(new java.awt.Color(255, 255, 255));
        jtfApellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfApellido.setEnabled(false);
        jPanel1.add(jtfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 195, -1));

        jbBuscar.setBackground(new java.awt.Color(102, 102, 255));
        jbBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbBuscar.setText("Buscar");
        jbBuscar.setEnabled(false);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jbGuardar.setBackground(new java.awt.Color(102, 102, 255));
        jbGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jbActualizar.setBackground(new java.awt.Color(102, 102, 255));
        jbActualizar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbActualizar.setText("Actualizar");
        jbActualizar.setEnabled(false);
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jbNuevo.setBackground(new java.awt.Color(102, 102, 255));
        jbNuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jbNuevo.setText("Nuevo");
        jbNuevo.setToolTipText("");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jbSalir.setBackground(new java.awt.Color(102, 102, 255));
        jbSalir.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, -1));
        jPanel1.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        limpiarCampos();
        activarCampos();
        jbActualizar.setEnabled(false);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        //funcionamiento
        if (jtfDni.getText().equals("") || jtfNombre.getText().equals("") || jtfApellido.getText().equals("") || jdcFecha.getDate() == null || !(jcbEstado.isSelected())) {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos exepto legajo");
        } else {

            int dni = Integer.parseInt(jtfDni.getText());
            String nombre = jtfNombre.getText();
            String apellido = jtfApellido.getText();
            Date input = jdcFecha.getDate();
            LocalDate fecha = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            boolean estado = jcbEstado.isSelected();
            Alumno alumno = new Alumno(dni, nombre, apellido, fecha, estado);
            ad.guardarAlumno(alumno);

            limpiarCampos();
            desactivarCampos();
        }


    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed

        int legajo = Integer.parseInt(jtfLegajo.getText());
        int dni = Integer.parseInt(jtfDni.getText());
        String nombre = jtfNombre.getText();
        String apellido = jtfApellido.getText();
        Date input = jdcFecha.getDate();
        boolean estado = jcbEstado.isSelected();
        LocalDate fecha = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Alumno alumno = new Alumno(legajo, dni, nombre, apellido, fecha, estado);
        ad.actualizarAlumno(alumno);
        limpiarCampos();
        desactivarCampos();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
          
        try {
            int legajo = Integer.parseInt(jtfLegajo.getText()); 
            Alumno alumno = ad.BuscarAlumnoXId(legajo);
             if (alumno.getDni() > 0) {
                 jtfDni.setText(alumno.getDni() + "");
                 jtfNombre.setText(alumno.getNombre());
                 jtfApellido.setText(alumno.getApellido());
                 jdcFecha.setDate(java.sql.Date.valueOf(alumno.getFechaNacimiento()));  
                 jcbEstado.setSelected(alumno.isEstado());
                 
                 jbActualizar.setEnabled(true);
                 jbGuardar.setEnabled(false);
        } else {
                 JOptionPane.showMessageDialog(this, " Alumno no encontrado");
                  jtfLegajo.requestFocus();
                  limpiarCampos();
                 }
          }
                catch (NumberFormatException ex){JOptionPane.showMessageDialog(this, "debe ingresar un número");
                        jtfLegajo.setText("");
                        jtfLegajo.requestFocus();
                        limpiarCampos();
                 }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtfLegajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfLegajoFocusLost
       /* try {
            int legajo = Integer.parseInt(jtfLegajo.getText());
        } catch (NumberFormatException exp) {
            if (!(jtfLegajo.getText().equals(""))) {
                JOptionPane.showMessageDialog(this, "Ingrese un legajo valido");
                jtfLegajo.requestFocus();
            }
        }*/
    }//GEN-LAST:event_jtfLegajoFocusLost

    private void jtfDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDniFocusLost
        try {
            int dni = Integer.parseInt(jtfDni.getText());
        } catch (NumberFormatException e) {

            if (!(jtfDni.getText().equals(""))) {
                JOptionPane.showMessageDialog(this, "Ingrese un dni valido");
                jtfDni.requestFocus();
            }
        }
    }//GEN-LAST:event_jtfDniFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcbEstado;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfLegajo;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
