/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AlumnoData;
import Controlador.InscripcionData;
import Controlador.MateriaData;
import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private AlumnoData ad;
    private MateriaData md;
    private InscripcionData iData;

    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion() {
        initComponents();
        modelo = new DefaultTableModel();
        ad = new AlumnoData();
        md = new MateriaData();
        iData = new InscripcionData();
        cargarCombo();
        armarCabecera();
    }

    private void cargarCombo() {
        for (Alumno x : ad.obtenerAlumnos()) {
            jcbAlumno.addItem(x);

        }
    }

    private void armarCabecera() {

        List<Object> columnas = new ArrayList<>();

        columnas.add("idMateria");
        columnas.add("nombre");
        columnas.add("año");

        for (Object x : columnas) {

            modelo.addColumn(x);

        }

        jtMateria.setModel(modelo);
    }

    private void borrarFilas() {

        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void recargainscripto(){

        borrarFilas();

        Alumno alumno = (Alumno) jcbAlumno.getSelectedItem();

        for (Materia x : iData.MateriasInscripto(alumno.getIdAlumno())) {

            modelo.addRow(new Object[]{x.getIdMateria(), x.getNombre(), x.getAnio()});
        }    
    }
    
    private void recargaNoInscripto(){
        
        borrarFilas();

        Alumno alumno = (Alumno) jcbAlumno.getSelectedItem();

        for (Materia x : iData.MateriaNoInscripto(alumno.getIdAlumno())) {

            modelo.addRow(new Object[]{x.getIdMateria(), x.getNombre(), x.getAnio()});

        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbInscriptas = new javax.swing.JRadioButton();
        jcbAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrbNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMateria = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jbAnular = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Formulario de inscripción");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jrbInscriptas.setBackground(new java.awt.Color(102, 102, 255));
        bgGrupo.add(jrbInscriptas);
        jrbInscriptas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbInscriptas.setText("Inscriptas");
        jrbInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInscriptasActionPerformed(evt);
            }
        });
        jPanel1.add(jrbInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jcbAlumno.setBackground(new java.awt.Color(102, 102, 255));
        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(jcbAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Listado de materias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jrbNoInscriptas.setBackground(new java.awt.Color(102, 102, 255));
        bgGrupo.add(jrbNoInscriptas);
        jrbNoInscriptas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbNoInscriptas.setText("No inscriptas");
        jrbNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNoInscriptasActionPerformed(evt);
            }
        });
        jPanel1.add(jrbNoInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jtMateria.setBackground(new java.awt.Color(102, 102, 255));
        jtMateria.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jtMateria.setForeground(new java.awt.Color(255, 255, 255));
        jtMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMateria.setGridColor(new java.awt.Color(51, 255, 255));
        jScrollPane1.setViewportView(jtMateria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 150));

        jbSalir.setBackground(new java.awt.Color(102, 102, 255));
        jbSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jbAnular.setBackground(new java.awt.Color(102, 102, 255));
        jbAnular.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbAnular.setText("Anular inscripcion");
        jbAnular.setEnabled(false);
        jbAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularActionPerformed(evt);
            }
        });
        jPanel1.add(jbAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jbGuardar.setBackground(new java.awt.Color(102, 102, 255));
        jbGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbGuardar.setText("Inscribir");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Alumno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrbInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInscriptasActionPerformed
        recargainscripto();
        jbGuardar.setEnabled(false);
        jbAnular.setEnabled(true);
    }//GEN-LAST:event_jrbInscriptasActionPerformed

    private void jrbNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNoInscriptasActionPerformed
        recargaNoInscripto();
        jbGuardar.setEnabled(true);
        jbAnular.setEnabled(false);
    }//GEN-LAST:event_jrbNoInscriptasActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        int fila = jtMateria.getSelectedRow();

        if (fila != -1) {

            int idMateria = (Integer) modelo.getValueAt(fila, 0);
            String nombre = (String) modelo.getValueAt(fila, 1);
            int anio = (Integer) modelo.getValueAt(fila, 2);
            Materia materia = new Materia(idMateria, anio, nombre, true);
            Alumno alumno = (Alumno) jcbAlumno.getSelectedItem();
            Inscripcion inscripto = new Inscripcion(0, materia, alumno);
            iData.agregarInscripcion(inscripto);
            recargaNoInscripto();
        } else {

            JOptionPane.showMessageDialog(this, "Seleccione un registro");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularActionPerformed
        int fila = jtMateria.getSelectedRow();

        if (fila != -1) {

            int idMateria = (Integer) modelo.getValueAt(fila, 0);
            Alumno alumno = (Alumno) jcbAlumno.getSelectedItem();

            iData.borrarInscripto(alumno.getIdAlumno(), idMateria);
            recargainscripto();
        } else {

            JOptionPane.showMessageDialog(this, "Seleccione un registro");
        }
    }//GEN-LAST:event_jbAnularActionPerformed

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        
    }//GEN-LAST:event_jcbAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnular;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcbAlumno;
    private javax.swing.JRadioButton jrbInscriptas;
    private javax.swing.JRadioButton jrbNoInscriptas;
    private javax.swing.JTable jtMateria;
    // End of variables declaration//GEN-END:variables
}
